apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/add-pod-topology-spread-constraints-patch.yaml
    target:
      group: apps
      kind: Deployment
      version: v1